name:                lambda
version:             0.1.0.0
license:             BSD3
author:              "John Hui, Stephen Edwards"
maintainer:          "sedwards@cs.columbia.edu"
copyright:           "2023 John Hui and Stephen Edwards"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - megaparsec
  - containers
  
executables:
  plc:
    main: Main.hs
    source-dirs: plc
    dependencies:
    - lambda
